#!/usr/bin/env node
/**
 * Compile packs-src/*.json (agent-extracted rulebook data) into Foundry
 * compendium packs under dist/packs/. Runs after `vite build` as part of
 * `npm run build`.
 *
 * - equipment: weapons + armor + ammo + gear (Item pack)
 * - npcs: creature statblocks (Actor pack); skill points are back-computed
 *   so derived bonuses match the printed numbers, pools/AC/DT use the
 *   override fields, and attacks become weapons with fixed to-hit.
 */

import { createHash } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { compilePack } from "@foundryvtt/foundryvtt-cli";

const root = path.dirname(path.dirname(new URL(import.meta.url).pathname));
const srcDir = path.join(root, "packs-src");
const outDir = path.join(root, "dist", "packs");

/** Deterministic 16-char Foundry id from a seed string. */
function foundryId(seed) {
  return createHash("sha1").update(seed).digest("base64url").replace(/[-_]/g, "a").slice(0, 16);
}

function readJson(name) {
  const file = path.join(srcDir, name);
  if (!fs.existsSync(file)) return [];
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

// ------------------------------------------------------------------ artwork

/**
 * Artwork generated by scripts/build-tokens.mjs from the vendored
 * game-icons.net SVGs. Documents point at the generated file when one exists
 * for their name and fall back to Foundry's stock icons otherwise.
 */
const assetsDir = path.join(root, "static", "assets");
const SYSTEM_ID = "fallout-ttrpg";
const SYSTEM_ASSETS = `systems/${SYSTEM_ID}/assets`;

/** Must stay in sync with slugify() in scripts/build-tokens.mjs. */
function slugify(name) {
  return String(name)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * @param {"tokens"|"icons"} kind directory under static/assets
 * @param {string} name document name
 * @param {string} fallback stock Foundry icon path
 */
function artwork(kind, name, fallback) {
  const slug = slugify(name);
  if (slug && fs.existsSync(path.join(assetsDir, kind, `${slug}.svg`))) {
    return `${SYSTEM_ASSETS}/${kind}/${slug}.svg`;
  }
  return fallback;
}

// ------------------------------------------------------------------- items

/**
 * The Vault-Tec Item Blueprint Encyclopedia (pg 94-115), joined onto the items
 * it describes so neither repair nor crafting has to ask for a DC.
 *
 * Two traps in this data, both flagged by the extraction pass:
 *
 * - **Both DC columns hold a bonus, not a DC** (pg 92-93). The check is against
 *   `10 + the printed number`, which is why the field is named `repairBonus`.
 * - **34 rows are modifier tables, not recipes.** Special Ammunition, Special
 *   Energy Weapons Ammunition and Syringes print a *delta* ("Reduce required
 *   lead by 1") against a base recipe, and have no time column at all. Joining
 *   those as absolute DCs would be wrong, so they are excluded by category.
 *   (The third id here used to read "syringes" and matched nothing — the
 *   extraction calls that category `syringes-special-ammunition`, so all twelve
 *   syringe rows were being treated as ordinary recipes.)
 */
const MODIFIER_CATEGORIES = new Set([
  "special-ammunition",
  "special-energy-weapons-ammunition",
  "syringes-special-ammunition",
]);

/**
 * Names the book itself spells two ways. Each was verified against the stat
 * table it disagrees with rather than guessed — "Scrap Metal" against "Metal"
 * is the book's own inconsistency between pg 56 and pg 94, not a typo here.
 *
 * A value may be an **array**, for the one Encyclopedia row that covers more
 * than one item: pg 115 prints a single blueprint headed "Pip-Boy 2000, 2000
 * Mark VI, 3000, 3000 Mark IV." against four separate pg 91 documents. The row
 * says "Cannot be crafted. Try one of those vaults." for all four, so fanning
 * it out copies a rule rather than inventing three.
 */
const BLUEPRINT_ALIASES = {
  "scrap metal": "Metal",
  "stimpack (diluted)": "Stimpak (Diluted)",
  "powered hazmat suit": "Hazmat Suit, Powered",
  "ranger sequoia": "Ranger Sequoia revolver",
  "t-45": "Power Armor: T-45",
  "t-51": "Power Armor: T-51",
  "t-60": "Power Armor: T-60",
  "x-01": "Power Armor: X-01",
  "x-02": "Power Armor: X-02",
  // The pack name encodes the "No. crafted" column the Encyclopedia prints in
  // a separate column ("Nails." crafts 5 at a time).
  nails: "Nails (Pack of 5)",
  ".308 rounds": ".308",
  // The four rows that used to be the whole "unstocked recipes" report: crafting
  // intermediates that are materials rather than equipment, and so had no
  // document until `junk.json`. Their documents carry the disambiguating "Junk:"
  // prefix (see the file list below for why), which is exactly what this table
  // exists to bridge.
  gunpowder: "Junk: Gunpowder",
  yeast: "Junk: Yeast",
  "alcohol yeast": "Junk: Alcohol Yeast",
  "power armor chassis": "Junk: Power Armor Chassis",
  "pip-boy 2000, 2000 mark vi, 3000, 3000 mark iv": [
    "Pip-Boy 2000",
    "Pip-Boy 2000 Mark VI",
    "Pip-Boy 3000",
    "Pip-Boy 3000 Mark IV",
  ],
};

/**
 * The upgrade and mod tables name their rows bare ("Insulated", "Bayonet")
 * while the compiled gear documents carry the table name as a prefix. Sixty of
 * the ninety-four rows the previous pass wrote off as "upgrades, not items" do
 * in fact ship as documents — and they are exactly the things a player crafts.
 * The prefix is per category, which also keeps the two "Light Build" rows and
 * the two "Strengthen" rows apart: they are different mods with different DCs.
 */
const CATEGORY_PREFIXES = {
  "armor-upgrades": "Armor Upgrade: ",
  "power-armor-upgrades": "Power Armor Upgrade: ",
  "melee-weapon-mods": "Melee Weapon Mod: ",
  "ranged-weapons-mods": "Ranged Weapon Mod: ",
};

/**
 * Name matching that survives the book's own punctuation. The Encyclopedia
 * prints "10mm." and "Bag, Backpack." with trailing periods the stat tables
 * omit, and "Doctors Bag" against the pack's "Doctor’s Bag" — a curly
 * apostrophe against no apostrophe at all.
 */
function blueprintKey(name) {
  return String(name)
    .toLowerCase()
    .replace(/[‘’']/g, "")
    .replace(/\.+\s*$/, "")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * The ammunition tables print a "No. of single ammunitions crafted" column and
 * two medicine rows carry an italic "(makes two)" rider; neither has a schema
 * key, so the extraction preserved both verbatim in `note`. Reading the count
 * back out is transcription, not invention — and without it, crafting nine
 * millimetre would make one round instead of twelve.
 */
function blueprintYield(row) {
  const note = row.note ?? "";
  const counted = /No\.\s*(?:of single ammunitions\s*)?crafted['"]?\s*[:=]\s*(\d+)/i.exec(note);
  if (counted) return Number(counted[1]);
  if (/\(makes two\)/i.test(note)) return 2;
  return 1;
}

const blueprintByName = new Map();
for (const row of readJson("blueprints.json")) {
  if (MODIFIER_CATEGORIES.has(row.category)) continue;
  const aliased = BLUEPRINT_ALIASES[blueprintKey(row.name)] ?? row.name;
  const prefix = CATEGORY_PREFIXES[row.category] ?? "";
  for (const name of Array.isArray(aliased) ? aliased : [aliased]) {
    const key = blueprintKey(`${prefix}${name}`);
    // Printed order wins on a duplicate; the later row is the anomaly.
    if (!blueprintByName.has(key)) blueprintByName.set(key, { ...row, yield: blueprintYield(row) });
  }
}
const blueprintsUsed = new Set();

// ---------------------------------------------------------- weapon mods (D3)

/**
 * The pg 65 and pg 75-77 weapon-modification tables, transcribed in
 * `packs-src/mods.json` and joined onto the gear documents that have shipped the
 * same 31 rows as prose since the equipment extraction.
 *
 * The join writes one field — `system.modKey` — which is the only machine-
 * readable thing about a mod document, and the seam an "attach this to that
 * weapon" control will need. Everything mechanical about a mod lives in
 * `src/rules/mods.ts`; this file's job is to make sure the two agree.
 *
 * **Two loud checks, for the same reason the backgrounds block above has its
 * own.** A mod key that stops matching is not a visible failure: nothing
 * throws, the document simply becomes unattachable, and the next person to look
 * finds a Silencer that cannot be fitted to anything and no explanation. So the
 * build fails outright when `mods.json` names a key `src/rules/mods.ts` does not
 * define, when it names a document `gear.json` does not ship, or when the two
 * key lists differ in either direction.
 */
const modRows = readJson("mods.json");
if (modRows.length > 0) {
  const module = fs.readFileSync(path.join(root, "src", "rules", "mods.ts"), "utf8");
  // The two `as const` key arrays, read as string literals. Deliberately not a
  // JSON parse of the file: these are two separate arrays with comments between
  // them, and the literals are the whole contract.
  const keysIn = (marker) => {
    const start = module.indexOf(marker);
    if (start === -1) throw new Error(`packs: cannot find ${marker} in src/rules/mods.ts`);
    const end = module.indexOf("] as const;", start);
    if (end === -1) throw new Error(`packs: ${marker} is not a closed 'as const' array`);
    return [...module.slice(start, end).matchAll(/"([A-Za-z]+)"/g)].map((match) => match[1]);
  };
  const declared = new Set([
    ...keysIn("export const RANGED_MOD_KEYS = ["),
    ...keysIn("export const MELEE_MOD_KEYS = ["),
  ]);

  const transcribed = new Set();
  for (const row of modRows) {
    if (!declared.has(row.key)) {
      throw new Error(
        `packs: mods.json row "${row.name}" has key "${row.key}", which src/rules/mods.ts does not declare`,
      );
    }
    if (transcribed.has(row.key)) {
      throw new Error(`packs: mods.json declares "${row.key}" twice`);
    }
    transcribed.add(row.key);
  }
  const missing = [...declared].filter((key) => !transcribed.has(key));
  if (missing.length > 0) {
    throw new Error(
      `packs: src/rules/mods.ts declares ${String(missing.length)} mod(s) that mods.json does not transcribe: ${missing.join(", ")}`,
    );
  }
}

/** `blueprintKey`-normalised document name -> mod key, for the join below. */
const modKeyByName = new Map(modRows.map((row) => [blueprintKey(row.name), row.key]));
const modKeysJoined = new Set();

const itemDocs = [];
for (const file of [
  "weapons.json",
  "armor.json",
  "ammo.json",
  "aid-food.json",
  "aid-med.json",
  "gear.json",
  // Crafting junk (BACKLOG D2). Its own file rather than a section of
  // `gear.json` because it is a census of the Encyclopedia's material columns
  // rather than a transcription of a stat table, and it is regenerated from
  // `blueprints.json` when that changes — see `packs-src/EXTRACTION-NOTES.md`.
  //
  // Every document is named "Junk: <material>", and the prefix is load-bearing:
  // three materials share a name with an armor type ("Steel", "Cloth",
  // "Leather"), and an unprefixed junk document would collide with that armor's
  // Encyclopedia row in `blueprintByName` below — handing a stack of steel the
  // steel armor's repair DC.
  "junk.json",
]) {
  for (const entry of readJson(file)) {
    const id = foundryId(`item:${entry.type}:${entry.name}`);
    // Only weapons, armor and gear carry decay, so only they have somewhere to
    // put a repair bonus. A `null` repair column means the book prints "–":
    // the item cannot be repaired at all, which is not the same as a DC of 10.
    const key = blueprintKey(entry.name);
    const blueprint = blueprintByName.get(key);
    const flags = {};
    // A mod document names itself to code (D3). Only `gear` carries the field,
    // and the name is the join because that is already how the crafting
    // blueprints for these same 31 rows find them.
    const modKey = modKeyByName.get(key);
    if (modKey !== undefined && entry.type === "gear") {
      entry.system.modKey = modKey;
      modKeysJoined.add(modKey);
    }
    if (blueprint) {
      blueprintsUsed.add(key);
      if (
        ["weapon", "armor", "gear"].includes(entry.type) &&
        typeof blueprint.repairBonus === "number"
      ) {
        entry.system.repairBonus = blueprint.repairBonus;
      }
      // The craft half of the row travels as a flag rather than as schema
      // fields. It has to reach armor, ammo and aid documents as well as
      // weapons and gear, and those five DataModels have nothing in common to
      // extend; a flag is one shape for all of them, needs no migration, and
      // keeps a static lookup table out of mutable actor state. Read by
      // src/actions/crafting.ts, which parses the mixed int|string|null DC
      // exactly as printed.
      flags[SYSTEM_ID] = { blueprint };
    }
    itemDocs.push({
      _id: id,
      _key: `!items!${id}`,
      name: entry.name,
      type: entry.type,
      img: artwork("icons", entry.name, "icons/svg/item-bag.svg"),
      system: entry.system,
      effects: [],
      folder: null,
      flags,
    });
  }
}

// --------------------------------------------------------- perks and traits

/**
 * The extraction agents annotate flat numeric bonuses as `mechanics` entries
 * keyed on the field a human would name. Those map onto the `system.bonuses.*`
 * fields the character model reserves for Active Effects — real schema fields,
 * so every change stays guided and validated rather than writing blindly into
 * computed data.
 */
function bonusKeyFor(key) {
  // Already canonical (hand-curated annotations write these directly):
  // a flat bonus, a per-skill bonus, or an advantage/disadvantage counter —
  // including the *scoped* counters, which take a third segment.
  //
  // The three-segment forms are what `advantagePath()`/`disadvantagePath()` in
  // src/rules/effects.ts produce, and what `character.ts` already stores and
  // reads (Power Armor writes `advantage.checks.radiation` today). They were
  // rejected here until the D4 audit found it: `CHECK_SCOPES` was added FOR
  // these perks, and not one of the ten could be emitted — Chemist, Stonewall,
  // Toughness rank 2, Spray and Pray, Can't Put Me Down, Street Rat and the
  // rest were text because of one missing alternation, not because anyone had
  // judged them unautomatable.
  if (
    /^system\.bonuses\.((advantage|disadvantage)\.(skills|checks)\.[A-Za-z]+|(skills|advantage|disadvantage)\.[A-Za-z]+|[A-Za-z]+)$/.test(
      key,
    )
  ) {
    return key;
  }
  const skill = /^system\.skills\.([A-Za-z]+)\.points$/.exec(key);
  if (skill) return `system.bonuses.skills.${skill[1]}`;
  const override = /^system\.overrides\.(ac|dt)$/.exec(key);
  if (override) return `system.bonuses.${override[1]}`;
  // Ability scores are a real base field already; effects may target them directly.
  if (/^system\.abilities\.[a-z]+\.value$/.test(key)) return key;
  return null;
}

/**
 * Build the embedded ActiveEffects for an entry's mechanics.
 *
 * **One effect per condition group, not one per item.** A perk can carry both
 * an unconditional clause and a conditional one — Hoarder (pg 32) is exactly
 * that shape: "Your Carry Load increases by 25. However, you have disadvantage
 * … while you're not carrying at least 50 load." A single effect cannot express
 * it, because the situations layer switches effects on and off *whole*: folding
 * both clauses together would make the +25 come and go with the load it is
 * supposed to help you reach.
 *
 * So mechanics are grouped by `condition` (and its `negate` flag). The
 * unconditional group, if any, is always enabled; each conditional group starts
 * disabled and is driven by `src/actions/situations.ts`, which reads the
 * `condition`/`conditionNegated` flags written here.
 */
function effectsFor(parentId, name, img, mechanics) {
  const groups = new Map();
  for (const mechanic of mechanics ?? []) {
    const key = bonusKeyFor(mechanic.key ?? "");
    if (!key || typeof mechanic.value !== "number" || mechanic.value === 0) {
      if (mechanic.key) unmappedMechanics.push(`${name}: ${mechanic.key}`);
      continue;
    }
    const condition = mechanic.condition ?? "";
    const negated = mechanic.negate === true;
    const groupKey = condition === "" ? "" : `${condition}:${negated ? "not" : "is"}`;
    if (!groups.has(groupKey)) groups.set(groupKey, { condition, negated, changes: [] });
    groups.get(groupKey).changes.push({
      key,
      // v14: `type` replaced the numeric `mode`; `initial` runs before the
      // derived pass, which is what folds bonuses into the sheet's numbers.
      type: mechanic.mode === "subtract" ? "subtract" : "add",
      value: mechanic.value,
      phase: "initial",
      priority: 20,
    });
  }

  const effects = [];
  for (const [groupKey, group] of groups) {
    // Suffixed so two groups on one perk get distinct ids, and so the id of an
    // unconditional effect is unchanged from before this split existed.
    const effectId = foundryId(`effect:${parentId}${groupKey === "" ? "" : `:${groupKey}`}`);
    const conditional = group.condition !== "";
    effects.push({
      _id: effectId,
      _key: `!items.effects!${parentId}.${effectId}`,
      // Named for the clause when there is more than one, so the sheet's
      // situational readout can say which half is waiting.
      name: conditional && groups.size > 1 ? `${name} (conditional)` : name,
      img,
      type: "base",
      // Transfers to whoever owns the perk, and reverts when it is removed.
      transfer: true,
      // A conditional effect starts switched off: the situation is not known to
      // hold until something evaluates it, and an effect that applied until the
      // first Sync would be wrong for exactly as long as nobody pressed it.
      disabled: conditional,
      system: { changes: group.changes },
      flags: conditional
        ? {
            "fallout-ttrpg": {
              condition: group.condition,
              ...(group.negated ? { conditionNegated: true } : {}),
            },
          }
        : {},
    });
  }
  return effects;
}

const unmappedMechanics = [];
const perkDocs = [];
for (const file of ["perks.json", "traits.json"]) {
  for (const entry of readJson(file)) {
    const id = foundryId(`item:${entry.type}:${entry.name}`);
    const img = artwork("icons", entry.name, "icons/svg/aura.svg");
    const effects = effectsFor(id, entry.name, img, entry.system.mechanics);
    // `mechanics` is an authoring aid, not part of the item schema.
    const { mechanics: _mechanics, ...system } = entry.system;
    perkDocs.push({
      _id: id,
      _key: `!items!${id}`,
      name: entry.name,
      type: entry.type,
      img,
      system,
      effects,
      folder: null,
      flags: {},
    });
  }
}

// -------------------------------------------------------------------- npcs

// Governing ability per skill — mirror of src/rules/constants.ts (defaults,
// not the alt options).
const SKILL_ABILITY = {
  barter: "charisma",
  breach: "perception",
  crafting: "intelligence",
  energyWeapons: "perception",
  explosives: "perception",
  guns: "agility",
  intimidation: "strength",
  medicine: "perception",
  meleeWeapons: "strength",
  science: "intelligence",
  sneak: "agility",
  speech: "charisma",
  survival: "endurance",
  unarmed: "strength",
};

const SKILL_NAME_LOOKUP = Object.fromEntries(
  Object.keys(SKILL_ABILITY).map((key) => [key.toLowerCase(), key]),
);
SKILL_NAME_LOOKUP["melee weapons"] = "meleeWeapons";
SKILL_NAME_LOOKUP["energy weapons"] = "energyWeapons";

const DAMAGE_TYPES = new Set([
  "acid", "ballistic", "bludgeoning", "cold", "electricity", "explosive",
  "fire", "impact", "laser", "piercing", "plasma", "poison", "slashing",
]);

function cleanName(name) {
  return name.replace(/[.,]\s*$/, "").replace(/,\s*/g, " ");
}

function npcWeaponType(attack) {
  const kind = (attack.attackType ?? "").toLowerCase();
  if (kind.includes("unarmed")) return "unarmed";
  if (kind.includes("melee") || attack.reach) return "blunt";
  return "handgun";
}

function firstDice(text) {
  const match = /\d+d\d+([+-]\d+)?/.exec(text ?? "");
  return match ? match[0] : "";
}

const npcDocs = [];
for (const npc of readJson("npcs.json")) {
  const name = cleanName(npc.name);
  const id = foundryId(`npc:${name}`);
  const mods = {};
  for (const [ability, score] of Object.entries(npc.abilities ?? {})) {
    mods[ability] = (score ?? 5) - 5;
  }
  const luckBonus = Math.floor((mods.luck ?? 0) / 2);

  const skills = {};
  for (const [rawName, bonus] of Object.entries(npc.skills ?? {})) {
    const key = SKILL_NAME_LOOKUP[rawName.trim().toLowerCase()];
    if (!key) continue;
    const governing = SKILL_ABILITY[key];
    skills[key] = {
      points: Math.max(0, bonus - (mods[governing] ?? 0) - luckBonus),
      useAlt: false,
    };
  }

  const items = (npc.attacks ?? []).map((attack) => {
    const itemId = foundryId(`npc:${name}:attack:${attack.name}`);
    const damage = firstDice(attack.damage);
    return {
      _id: itemId,
      // Embedded docs need their own LevelDB key inside the parent's scope.
      _key: `!actors.items!${id}.${itemId}`,
      name: attack.name,
      type: "weapon",
      img: artwork("icons", attack.name, "icons/svg/sword.svg"),
      system: {
        weaponType: npcWeaponType(attack),
        apCost: attack.apCost ?? 4,
        damage: damage || "0",
        damageType: DAMAGE_TYPES.has((attack.damageType ?? "").toLowerCase())
          ? attack.damageType.toLowerCase()
          : "",
        critChance: attack.critChance ?? 20,
        crit: "x2",
        special: [attack.range, attack.special].filter(Boolean).join(" — "),
        ...(typeof attack.toHit === "number" ? { attackBonusOverride: attack.toHit } : {}),
      },
      effects: [],
      flags: {},
    };
  });

  const bioParts = [];
  if (npc.size || npc.type) bioParts.push(`<p><em>${[npc.size, npc.type].filter(Boolean).join(" ")}</em> (pg ${npc.page ?? "?"})</p>`);
  for (const list of ["immunities", "conditionImmunities"]) {
    const values = npc[list] ?? [];
    if (values.length) bioParts.push(`<p><strong>${list === "immunities" ? "Damage immunities" : "Condition immunities"}:</strong> ${values.join(", ")}</p>`);
  }
  for (const trait of npc.traits ?? []) {
    bioParts.push(`<p><strong>${trait.name}.</strong> ${trait.text}</p>`);
  }
  if (npc.loot) bioParts.push(`<p><strong>Loot:</strong> ${npc.loot}</p>`);
  if (npc.notes) bioParts.push(`<p><em>Extraction note: ${npc.notes}</em></p>`);

  const token = artwork("tokens", name, "icons/svg/mystery-man.svg");
  npcDocs.push({
    _id: id,
    _key: `!actors!${id}`,
    name,
    type: "npc",
    img: token,
    prototypeToken: { texture: { src: token } },
    system: {
      abilities: Object.fromEntries(
        Object.entries(npc.abilities ?? {}).map(([ability, score]) => [ability, { value: score }]),
      ),
      skills,
      resources: {
        hp: { value: npc.hp ?? 10 },
        sp: { value: npc.sp ?? 0 },
        ap: { value: npc.ap ?? 10 },
      },
      overrides: {
        hpMax: npc.hp ?? null,
        spMax: npc.sp ?? 0,
        apMax: npc.ap ?? null,
        ac: npc.ac ?? null,
        dt: npc.dt ?? null,
      },
      defenses: {
        resistances: (npc.resistances ?? []).join(", "),
        vulnerabilities: (npc.vulnerabilities ?? []).join(", "),
      },
      details: {
        race: npc.type ?? "creature",
        level: 1,
        biography: bioParts.join("\n"),
      },
    },
    items,
    effects: [],
    folder: null,
    flags: {},
  });
}

// The other half of the mod join: every transcribed row must have found a
// document. Fatal rather than reported — an unattachable mod is a silent hole,
// and `gear.json` has shipped all 31 of these since the equipment extraction, so
// a miss here means a name drifted.
if (modRows.length > 0) {
  const unjoined = modRows.filter((row) => !modKeysJoined.has(row.key));
  if (unjoined.length > 0) {
    throw new Error(
      `packs: ${String(unjoined.length)} mod(s) in mods.json match no shipped gear document: ` +
        unjoined.map((row) => row.name).join(", "),
    );
  }
  console.log(`packs: ${String(modKeysJoined.size)} weapon mod(s) keyed onto gear documents`);
}

// ----------------------------------------------------------- backgrounds

/**
 * Backgrounds (pg 13-18) are **not compiled into a pack**, and this block is
 * why the build still has to look at them.
 *
 * A background is not any of the seven Item types this system declares, so a
 * compendium home for one would need a DataModel, an entry in
 * `static/system.json` and a sheet before a single +2 could reach a character.
 * It is also read during a synchronous sheet render, which a pack cannot serve.
 * So the data ships as a typed constant in `src/rules/backgrounds.ts`, emitted
 * from `packs-src/backgrounds.json`.
 *
 * Two copies of one table is exactly the arrangement that rots, so the build
 * refuses to proceed when they differ, and reports every kit clause that names
 * an item no pack ships. That second check is the one with teeth: a background
 * is the only thing in this system that hands a player twenty-five documents
 * at once, and a name that stops matching is twenty-four items and a silence.
 */
const backgrounds = readJson("backgrounds.json");
if (backgrounds.length > 0) {
  const module = fs.readFileSync(path.join(root, "src", "rules", "backgrounds.ts"), "utf8");
  const marker = "export const BACKGROUNDS: readonly Background[] = ";
  const start = module.indexOf(marker);
  const end = module.indexOf("\n];\n", start);
  if (start === -1 || end === -1) {
    throw new Error("packs: cannot find BACKGROUNDS in src/rules/backgrounds.ts");
  }
  const inlined = JSON.parse(module.slice(start + marker.length, end + 2));
  if (JSON.stringify(inlined) !== JSON.stringify(backgrounds)) {
    throw new Error(
      "packs: src/rules/backgrounds.ts has drifted from packs-src/backgrounds.json — " +
        "re-emit the BACKGROUNDS constant from the JSON",
    );
  }

  const shippedNames = new Set(itemDocs.map((doc) => blueprintKey(doc.name)));
  const unstocked = new Set();
  let kits = 0;
  let clauses = 0;
  let reported = 0;
  for (const background of backgrounds) {
    for (const kit of background.kits) {
      kits += 1;
      for (const entry of kit.items) {
        clauses += 1;
        if (entry.name === null) reported += 1;
        else if (!shippedNames.has(blueprintKey(entry.name))) unstocked.add(entry.name);
      }
    }
  }
  console.log(
    `packs: ${backgrounds.length} backgrounds verified against src/rules/backgrounds.ts ` +
      `(${kits} kits, ${clauses} clauses, ${reported} reported rather than granted)`,
  );
  // Loud on purpose, in the same spirit as the blueprint join below: a kit
  // clause that resolves to a name no pack ships is an item the player is
  // promised and never handed.
  if (unstocked.size > 0) {
    console.log(`packs: ${unstocked.size} background item(s) name no shipped document:`);
    for (const name of [...unstocked].sort()) console.log(`  - ${name}`);
  }
}

// ----------------------------------------------------------------- compile

async function build(packName, docs) {
  if (docs.length === 0) {
    console.log(`packs: skipping ${packName} (no source data)`);
    return;
  }
  const staging = fs.mkdtempSync(path.join(os.tmpdir(), `fallout-pack-${packName}-`));
  for (const doc of docs) {
    fs.writeFileSync(path.join(staging, `${doc._id}.json`), JSON.stringify(doc, null, 2));
  }
  const dest = path.join(outDir, packName);
  fs.mkdirSync(dest, { recursive: true });
  await compilePack(staging, dest, { log: false });
  fs.rmSync(staging, { recursive: true, force: true });
  console.log(`packs: compiled ${packName} (${docs.length} documents)`);
}

fs.mkdirSync(outDir, { recursive: true });
await build("equipment", itemDocs);
await build("perks", perkDocs);
await build("npcs", npcDocs);

if (unmappedMechanics.length > 0) {
  console.log(
    `packs: ${unmappedMechanics.length} mechanics annotation(s) had no bonus field and stayed text`,
  );
  for (const entry of unmappedMechanics) console.log(`  - ${entry}`);
}
// Loud on purpose: a name that stops matching is how a repair DC silently
// reverts to "ask the player", and the build printing it is what catches it.
const joined = blueprintsUsed.size;
const orphans = [...blueprintByName.keys()].filter((key) => !blueprintsUsed.has(key));
// "Craftable" means the row prints a Craft DC at all: 21 rows print "-" for
// "Cannot be crafted", which is a rule rather than missing data.
const craftable = itemDocs.filter(
  (doc) => (doc.flags[SYSTEM_ID]?.blueprint?.craftDC ?? null) !== null,
).length;
console.log(
  `packs: ${joined} blueprint(s) joined onto equipment (${craftable} craftable), ` +
    `${orphans.length} with no matching item`,
);
if (orphans.length > 0) {
  // What is left after the prefix join is real: crafting intermediates the
  // packs never shipped (Gunpowder, Power Armor Chassis, Yeast, Alcohol Yeast)
  // and the six pg 115 unique items, which have no equipment document at all.
  console.log(`  (unstocked recipes — ${orphans.slice(0, 8).join(", ")}…)`);
}

const withEffects = perkDocs.filter((doc) => doc.effects.length > 0).length;
if (perkDocs.length > 0) {
  console.log(`packs: ${withEffects} of ${perkDocs.length} perks/traits carry an Active Effect`);
}
